---
- name: install Docker
  become: true
  hosts: manager
  roles:
  - docker

- name: install Docker
  become: true
  hosts: worker
  roles:
  - docker

- name : initialize docker swarm
  become: true
  hosts: manager
  roles:
  - manager

- name: join worker to docker-swarm
  become: true
  hosts: worker
  roles:
  - worker